### ISSUE TITLE
Will you support more cloud providers?

### ISSUE THREAD

**Issue by nluo** [samuelhbne/vpn-launchpad#5]

**Comment by nluo** [comment]
The tool is great and works very good on AWS. Will you support more cloud providers?

**Comment by samuelhbne** [comment]
Thanks Nluo.

Unfortunately, Google cloud command centre is unreachable from China, which makes it vary unlikely to be an infrastructure of anti-censorship. Actually, a deploy-only option is in progress of development to decouple the binding with AWS. As the next step of non-AWS cloud support.

Thanks.

**Comment by nluo** [comment]
Thanks!

**Comment by nluo** [comment]
I will close the issue then!
