### ISSUE TITLE
Is it possible to deploy multipe instances without purging the old instance?

### ISSUE THREAD

**Issue by nluo** [samuelhbne/vpn-launchpad#6]
e.g., I have deployed my instance to sydney region, but I want have multiple instances in sydney region, now will ask me to purge first.

**Comment by samuelhbne** [comment]
Yes it is possible. But the 2nd server should located in different region. Say: one in ap-northeast-1 and one in ap-northeast-2.

https://github.com/samuelhbne/vpn-launchpad/blob/master/FAQ.md#can-i-build-multiple-vpn-servers-with-the-same-aws-account

**Comment by nluo** [comment]
Got it, thanks 👍
